// GENERATED by tools/trace_cad/emit_ts.py — do not edit by hand.
/** Shared floor frame: every level is drawn in this coordinate box. */
export const FRAME = { width: 3182, height: 1591 };
/** Sheet point (upper-floor PDFs) at the frame origin; lets one floor be regenerated alone. */
export const ORIGIN = { x: 58, y: 424 };
