// GENERATED by tools/trace_signs/gen.py from the wayfinding sign photos — do not edit by hand.
// Level One: rooms traced from the Level One whole-floor sign and the Level 1 Northeast detail sign (no Southwest detail sign exists; the Southwest block is traced from the whole-floor sign).
// Coordinates are floor-frame units (see outline.ts). Perimeter vertices are snapped onto the
// outline walls and shared corners are welded, so rooms meet the exterior walls exactly.
import type { PoiSpec, RoomSpec } from './floor';

export const rooms: RoomSpec[] = [
  ['Northeast', '1130', 'open', [[1131.7, 71.1], [1120.4, 148.6], [1055.2, 166.4], [810.6, 212.0], [802.7, 207.8], [800.3, 133.9]]],
  ['Northeast', '1161', 'meeting', [[1136.1, 125.6], [1140.2, 59.2], [1175.0, 51.6], [1168.5, 118.4]]],
  ['Northeast', '1163', 'office', [[1173.2, 118.6], [1175.0, 51.6], [1209.8, 43.9], [1208.4, 108.3]]],
  ['Northeast', '1167', 'office', [[1244.6, 36.2], [1243.2, 101.3], [1208.4, 108.3], [1215.3, 42.7]]],
  ['Northeast', '1169', 'office', [[1249.1, 97.6], [1250.9, 34.9], [1282.5, 27.9], [1283.8, 88.9]]],
  ['Northeast', '1171', 'meeting', [[1300.1, 24.1], [1312.2, 21.4], [1361.6, 71.7], [1307.5, 119.3], [1287.4, 92.4], [1288.4, 26.6]]],
  ['Northeast', '1173', 'office', [[1386.6, 97.1], [1391.0, 101.7], [1350.1, 138.5], [1322.5, 118.6], [1358.3, 81.8], [1367.6, 77.8]]],
  ['Northeast', '1175', 'office', [[1414.5, 125.6], [1375.6, 165.3], [1369.1, 166.5], [1352.4, 152.9], [1350.1, 138.5], [1391.0, 101.7], [1395.2, 106.0]]],
  ['Northeast', '1179', 'office', [[1441.0, 152.6], [1400.9, 192.2], [1391.1, 195.4], [1373.6, 174.0], [1403.0, 144.0], [1421.4, 132.7]]],
  ['Northeast', '1181', 'focus', [[1465.5, 177.5], [1463.5, 189.0], [1426.0, 219.8], [1416.4, 221.9], [1400.3, 199.4], [1433.9, 167.0], [1448.0, 159.7]]],
  ['Northeast', '1183', 'meeting', [[1503.9, 216.6], [1498.9, 225.9], [1409.2, 257.5], [1400.4, 251.4], [1472.4, 184.5]]],
  ['Northeast', '1134', 'office', [[950.5, 235.3], [905.6, 243.5], [908.6, 206.3], [954.5, 196.5]]],
  ['Northeast', '1136', 'focus', [[1002.1, 226.7], [950.5, 235.3], [954.5, 196.5], [1006.9, 187.6]]],
  ['Northeast', '1138', 'focus', [[1047.4, 221.0], [1011.9, 228.8], [1002.1, 226.7], [1006.9, 187.6], [1044.7, 178.7], [1053.1, 185.1]]],
  ['Northeast', '1142', 'office', [[1047.0, 229.1], [1040.2, 268.7], [1000.0, 272.8], [1005.2, 232.5], [1032.7, 225.7]]],
  ['Northeast', '1144', 'office', [[1042.8, 275.9], [1034.1, 317.1], [1003.2, 321.8], [996.3, 315.3], [1003.0, 278.5]]],
  ['Northeast', '1143', 'office', [[1113.6, 241.5], [1076.0, 248.2], [1068.1, 244.3], [1077.1, 201.6], [1122.4, 195.4]]],
  ['Northeast', '1153', 'office', [[1166.9, 229.5], [1128.5, 238.6], [1119.2, 235.1], [1128.1, 191.7], [1173.7, 183.4]]],
  ['Northeast', '1145', 'office', [[1108.3, 293.3], [1061.4, 295.1], [1070.2, 252.9], [1113.9, 247.1]]],
  ['Northeast', '1155', 'office', [[1165.3, 234.9], [1158.7, 278.5], [1112.0, 288.1], [1118.3, 244.7]]],
  ['Northeast', '1147', 'office', [[1099.0, 339.5], [1061.3, 345.8], [1056.1, 342.3], [1063.0, 302.1], [1108.3, 293.3]]],
  ['Northeast', '1157', 'office', [[1151.9, 325.8], [1104.1, 337.5], [1108.3, 293.3], [1158.0, 283.9]]],
  ['Northeast', '1154', 'office', [[1253.3, 162.1], [1250.6, 203.4], [1195.3, 218.7], [1205.2, 174.3]]],
  ['Northeast', '1156', 'office', [[1251.4, 208.5], [1245.3, 250.6], [1190.0, 270.6], [1198.2, 222.6]]],
  ['Northeast', '1158', 'office', [[1244.8, 255.8], [1238.0, 298.2], [1181.9, 317.2], [1190.0, 270.6]]],
  ['Northeast', 'ne-room-1', 'office', [[903.1, 232.0], [880.9, 303.0], [839.9, 309.2], [839.7, 242.3]], { name: 'Unlabelled room', label: '', tags: ['unlabelled'] }],
  ['Northeast', 'ne-room-2', 'office', [[813.0, 315.6], [813.9, 246.8], [839.7, 242.3], [839.9, 309.2], [830.6, 315.0]], { name: 'Unlabelled room', label: '', tags: ['unlabelled'] }],
  ['Northeast', '1110B', 'meeting', [[739.3, 351.1], [708.7, 356.7], [701.2, 288.7], [734.0, 284.5]], { name: 'Meeting Room 1110B' }],
  ['Northeast', '1110A', 'meeting', [[746.7, 416.4], [714.1, 422.0], [708.7, 356.7], [739.3, 351.1]], { name: 'Meeting Room 1110A' }],
  ['Northeast', '1110', 'open', [[697.6, 291.6], [709.2, 422.5], [637.6, 428.6], [663.2, 296.7]]],
  ['Northeast', 'ne-stair-2', 'circulation', [[783.3, 306.5], [783.3, 358.3], [768.3, 358.4], [751.5, 385.6], [755.1, 394.0], [769.5, 399.5], [786.5, 385.6], [788.1, 410.3], [746.7, 416.4], [740.4, 313.7]], { name: 'Northeast Stair (north)', label: 'Stair', tags: ['stairs'] }],
  ['Northeast', 'ne-mens-restroom', 'service', [[890.9, 219.5], [1011.9, 228.8], [988.7, 330.5], [877.3, 315.8]], { name: 'Men’s Restroom (NE)', label: 'Men’s WC', tags: ['restroom', 'men'] }],
  ['Northeast', 'ne-elevator', 'circulation', [[793.7, 315.9], [861.1, 323.0], [852.9, 394.6], [786.5, 385.6]], { name: 'Northeast Elevator', label: 'Elevator', tags: ['elevator'] }],
  ['Northeast', 'ne-stair', 'circulation', [[970.5, 390.3], [884.5, 400.3], [885.5, 340.1], [974.8, 329.1]], { name: 'Northeast Stair', label: 'Stair', tags: ['stairs'] }],
  ['Northeast', 'ne-all-gender-restroom', 'service', [[1004.3, 328.4], [1053.6, 335.2], [1041.1, 396.7], [993.4, 389.1]], { name: 'All-Gender Restroom (NE)', label: 'All-gender WC', tags: ['restroom', 'all gender'] }],
  ['Northeast', 'meditation-room', 'amenity', [[746.3, 271.1], [784.4, 273.0], [781.9, 313.2], [745.0, 309.8]], { name: 'Meditation Room', label: 'Meditation', tags: ['wellness', 'quiet'] }],
  ['Northeast', 'lactation-room', 'amenity', [[784.4, 273.0], [815.3, 274.1], [813.0, 315.6], [781.9, 313.2]], { name: 'Lactation Room', label: 'Lactation', tags: ['wellness'] }],
  ['Northeast', '1210', 'classroom', [[1175.8, 464.1], [1184.2, 415.5], [1200.4, 393.9], [1463.9, 286.5], [1486.0, 299.8], [1534.6, 344.7], [1541.1, 357.7], [1539.2, 373.1], [1442.8, 566.0], [1420.3, 579.4], [1392.4, 573.6]], { name: 'Lecture Hall 1210' }],
  ['Northeast', '1220', 'classroom', [[1416.7, 599.6], [1520.8, 425.6], [1536.2, 407.5], [1565.0, 394.8], [1590.6, 396.6], [1798.5, 599.3], [1762.1, 628.1], [1501.5, 690.8]], { name: 'Lecture Hall 1220' }],
  ['Northeast', '1230', 'lab', [[1514.4, 704.7], [1810.0, 611.7], [1908.4, 714.0], [1583.2, 778.5]], { name: 'Drone Lab 1230' }],
  ['Southwest', 'sw-stair-2', 'circulation', [[281.0, 315.6], [344.8, 302.4], [358.5, 376.7], [294.6, 387.7]], { name: 'Southwest Stair (north)', label: 'Stair', tags: ['stairs'] }],
  ['Southwest', 'sw-room-1', 'open', [[134.2, 397.8], [261.9, 373.6], [288.8, 511.4], [161.1, 535.5]], { name: 'Open workspace', label: '', tags: ['unlabelled'] }],
  ['Southwest', 'sw-elevator', 'circulation', [[215.8, 563.4], [269.3, 560.8], [276.0, 619.7], [222.5, 622.3]], { name: 'Southwest Elevator', label: 'Elevator', tags: ['elevator'] }],
  ['Southwest', 'sw-restrooms', 'service', [[273.5, 556.6], [369.3, 542.3], [380.9, 616.5], [282.7, 626.4]], { name: 'Restrooms (SW)', label: 'WC', tags: ['restroom', 'women', 'men', 'all gender'] }],
  ['Southwest', 'sw-stair', 'circulation', [[315.2, 636.1], [379.1, 625.2], [392.6, 695.1], [328.7, 706.1]], { name: 'Southwest Stair', label: 'Stair', tags: ['stairs'] }],
  ['Southwest', 'sw-room-2', 'office', [[329.2, 719.2], [414.4, 704.5], [440.0, 809.7], [354.9, 824.3]], { name: 'Unlabelled room', label: '', tags: ['unlabelled'] }],
];

export const pois: PoiSpec[] = [
  ['ne-kitchen', 'Northeast social kitchen', 'cafe', [737.2, 205.4]],
  ['ne-porch', 'Northeast front porch', 'porch', [1135.6, 380.7]],
  ['sw-porch', 'Southwest front porch', 'porch', [356.4, 594.0]],
  ['ne-entrance', 'Northeast entrance', 'exit', [1133.7, 56.5]],
  ['sw-entrance', 'Southwest entrance', 'exit', [349.9, 961.6]],
  ['east-stair', 'East stair', 'stairs', [1579.2, 694.5]],
];

/** Centre and radii of the atrium stair ellipse as drawn on the whole-floor sign. */
export const atrium = { cx: 852.4, cy: 502.0, rx: 155.3, ry: 88.8 };
