import json
SRC={'1':('level1','Level One','the Level One whole-floor sign and the Level 1 Northeast detail sign (no Southwest detail sign exists; the Southwest block is traced from the whole-floor sign)'),
     '2':('level2','Level Two','the Level 2 Northeast and Southwest detail signs'),
     '3':('level3','Level Three','the Level 3 Northeast and Southwest detail signs')}
def q(s): return "'"+s.replace("\\","\\\\").replace("'","\\'")+"'"
for f,(mod,title,src) in SRC.items():
    d=json.load(open(f'floor{f}.json'))
    L=[]; A=L.append
    A("// GENERATED by tools/trace_signs/gen.py from the wayfinding sign photos — do not edit by hand.")
    A(f"// {title}: rooms traced from {src}.")
    A("// Coordinates are floor-frame units (see outline.ts). Perimeter vertices are snapped onto the")
    A("// outline walls and shared corners are welded, so rooms meet the exterior walls exactly.")
    A("import type { PoiSpec, RoomSpec } from './floor';")
    A("")
    A("export const rooms: RoomSpec[] = [")
    for r in d['rooms']:
        poly=', '.join(f"[{x}, {y}]" for x,y in r['poly'])
        extra={}
        for k in ['name','label','description','tags']:
            if k in r and r[k] is not None: extra[k]=r[k]
        if extra:
            parts=[]
            for k,v in extra.items():
                parts.append(f"{k}: {q(v)}" if isinstance(v,str) else f"{k}: [{', '.join(q(t) for t in v)}]")
            ex=', { '+', '.join(parts)+' }'
        else: ex=''
        A(f"  [{q(r['wing'])}, {q(r['id'])}, {q(r['cat'])}, [{poly}]{ex}],")
    A("];")
    A("")
    A("export const pois: PoiSpec[] = [")
    for p in d['pois']:
        A(f"  [{q(p['id'])}, {q(p['name'])}, {q(p['kind'])}, [{p['at'][0]}, {p['at'][1]}]],")
    A("];")
    A("")
    c=d['atrium']['c']; r=d['atrium']['r']
    A(f"/** Centre and radii of the atrium stair ellipse as drawn on the whole-floor sign. */")
    A(f"export const atrium = {{ cx: {round(c[0],1)}, cy: {round(c[1],1)}, rx: {round(r[0],1)}, ry: {round(r[1],1)} }};")
    open(f'/workspace/gateway-map/src/data/gateway/{mod}.ts','w').write('\n'.join(L)+'\n')
    print(mod,'rooms',len(d['rooms']))
