"""Write src/data/gateway/level*.ts from the <floor>_rooms.json files.

Usage: python3 emit_ts.py <workdir> <src/data/gateway dir>

Every floor is mapped into one shared frame: the PDF point grid of the upper-floor sheets
(which are all drawn in the same position), shifted so the building starts near the origin.
The Lower Level sheet is drawn at another scale and rotation and is registered with the
similarity transform in floors.py.
"""
import json
import math
import os
import sys

from floors import FLOORS, category, display_name, wing

PAD = 20.0


def similarity(t):
    if not t:
        return lambda x, y: (x, y)
    s, deg, dx, dy = t
    c, si = math.cos(math.radians(deg)) * s, math.sin(math.radians(deg)) * s
    return lambda x, y: (c * x - si * y + dx, si * x + c * y + dy)


def load(workdir):
    data = {}
    for fid, cfg in FLOORS.items():
        path = os.path.join(workdir, f"{cfg['pdf']}_rooms.json")
        if not os.path.exists(path):
            print('missing', path)
            continue
        data[fid] = json.load(open(path))
    return data


def frame(data):
    xs, ys = [], []
    for fid, d in data.items():
        tf = similarity(FLOORS[fid]['transform'])
        for o in d['outlines']:
            for x, y in o:
                X, Y = tf(x, y)
                xs.append(X)
                ys.append(Y)
    x0, y0 = min(xs) - PAD, min(ys) - PAD
    return x0, y0, max(xs) - x0 + PAD, max(ys) - y0 + PAD


def fmt_poly(poly):
    return '[' + ', '.join(f'[{x:.1f}, {y:.1f}]' for x, y in poly) + ']'


def ts_str(s):
    return "'" + s.replace('\\', '\\\\').replace("'", "\\'") + "'"


def emit_floor(fid, d, x0, y0, out_dir):
    cfg = FLOORS[fid]
    tf = similarity(cfg['transform'])
    to_frame = lambda poly: [(lambda p: (p[0] - x0, p[1] - y0))(tf(x, y)) for x, y in poly]
    lines = []
    lines.append(f"// GENERATED by tools/trace_cad/emit_ts.py from the CAD plan 'Gateway_Plan_View_10_2_2025-Floor_{cfg['pdf']}.pdf' — do not edit by hand.")
    lines.append('// Coordinates are the shared floor frame (PDF points of the upper-floor sheets, origin shifted; see tools/trace_cad/README.md).')
    lines.append("import type { PoiSpec, RoomSpec } from './floor';")
    lines.append("import type { XY } from '../helpers';")
    lines.append('')
    outlines = [to_frame(o) for o in d['outlines']]
    lines.append(f'export const outline: XY[] = {fmt_poly(outlines[0])};')
    lines.append('export const islands: XY[][] = [' + ', '.join(fmt_poly(o) for o in outlines[1:]) + '];')
    lines.append('')
    lines.append('export const rooms: RoomSpec[] = [')
    seen = {}
    for r in sorted(d['rooms'], key=lambda r: (r['kind'] != 'room', r['id'])):
        if r['id'] in cfg['skip'] or not r.get('polygon'):
            continue
        rid = r['id']
        seen[rid] = seen.get(rid, 0) + 1
        if seen[rid] > 1:
            rid = f"{rid}-{seen[rid]}"
        cat = category(r['name'], r['id'])
        name = display_name(r['name'], r['id'])
        w = wing(r['id'])
        extra = {'name': name, 'label': r['id']}
        tags = [t for t in r['name'].lower().replace('/', ' ').split() if len(t) > 2 and t not in {'the', 'and'}]
        if r['kind'] == 'open':
            tags.append('open plan')
        if tags:
            extra['tags'] = tags
        lines.append(f"  [{ts_str(w) if w else 'undefined'}, {ts_str(rid)}, {ts_str(cat)}, {fmt_poly(to_frame(r['polygon']))}, {fmt_extra(extra)}],")
    for px, py, uid, cat, name, label, tags in cfg['named']:
        points = px if isinstance(px, list) else [(px, py)]
        regions = []
        for qx, qy in points:
            u = region_at(d['unlabelled'], qx, qy)
            if u is not None and all(u is not r for r in regions):
                regions.append(u)
        if not regions:
            print(f'  floor {fid}: no unlabelled region at {points} for {uid}')
            continue
        poly = regions[0]['polygon'] if len(regions) == 1 else union_polys([r['polygon'] for r in regions])
        extra = {'name': name, 'label': label, 'tags': tags}
        w = wing(uid) or ('Northeast' if uid.startswith('ne-') else 'Southwest' if uid.startswith('sw-') else None)
        lines.append(f"  [{ts_str(w) if w else 'undefined'}, {ts_str(uid)}, {ts_str(cat)}, {fmt_poly(to_frame(poly))}, {fmt_extra(extra)}],")
    for uid, cat, name, label, tags, poly in cfg['manual']:
        extra = {'name': name, 'label': label, 'tags': tags}
        w = wing(uid)
        poly = clip_to(poly, d['outlines'])
        lines.append(f"  [{ts_str(w) if w else 'undefined'}, {ts_str(uid)}, {ts_str(cat)}, {fmt_poly(to_frame(poly))}, {fmt_extra(extra)}],")
    lines.append('];')
    lines.append('')
    lines.append('export const pois: PoiSpec[] = [')
    for i, (ex, ey) in enumerate(d.get('exits', []), 1):
        X, Y = tf(ex, ey)
        lines.append(f"  ['entrance-{i}', 'Entrance {i}', 'exit', [{X - x0:.1f}, {Y - y0:.1f}]],")
    for pid, name, kind, (px, py), *desc in cfg['pois']:
        X, Y = tf(px, py)
        lines.append(f"  [{ts_str(pid)}, {ts_str(name)}, {ts_str(kind)}, [{X - x0:.1f}, {Y - y0:.1f}]{', ' + ts_str(desc[0]) if desc else ''}],")
    lines.append('];')
    lines.append('')
    open(os.path.join(out_dir, f'level{fid}.ts'), 'w').write('\n'.join(lines))
    print(f'level{fid}.ts: {len(d["rooms"])} rooms + {len(cfg["named"])} named regions')


def clip_to(poly, outlines):
    """Intersection of a hand polygon with the floor outline(s), via a 1 px/pt raster."""
    import cv2
    import numpy as np
    pts = np.array(poly, np.float32)
    x0, y0 = np.floor(pts.min(0)).astype(int) - 2
    x1, y1 = np.ceil(pts.max(0)).astype(int) + 2
    a = np.zeros((y1 - y0, x1 - x0), np.uint8)
    b = np.zeros_like(a)
    cv2.fillPoly(a, [np.round(pts - [x0, y0]).astype(np.int32)], 255)
    for o in outlines:
        cv2.fillPoly(b, [np.round(np.array(o) - [x0, y0]).astype(np.int32)], 255)
    cs, _ = cv2.findContours(a & b, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
    if not cs:
        return poly
    c = cv2.approxPolyDP(max(cs, key=cv2.contourArea), 1.5, True).reshape(-1, 2) + [x0, y0]
    return [[float(x), float(y)] for x, y in c]


def union_polys(polys):
    """Outer contour of the union of polygons (closed by a few px so touching flights join)."""
    import cv2
    import numpy as np
    pts = np.concatenate([np.array(p, np.float32) for p in polys])
    x0, y0 = np.floor(pts.min(0)).astype(int) - 6
    x1, y1 = np.ceil(pts.max(0)).astype(int) + 6
    a = np.zeros((y1 - y0, x1 - x0), np.uint8)
    for p in polys:
        cv2.fillPoly(a, [np.round(np.array(p) - [x0, y0]).astype(np.int32)], 255)
    a = cv2.morphologyEx(a, cv2.MORPH_CLOSE, np.ones((9, 9), np.uint8))
    cs, _ = cv2.findContours(a, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
    c = cv2.approxPolyDP(max(cs, key=cv2.contourArea), 1.5, True).reshape(-1, 2) + [x0, y0]
    return [[float(x), float(y)] for x, y in c]


def region_at(unlabelled, x, y):
    """The unlabelled region whose polygon contains (x, y), smallest first."""
    import cv2
    import numpy as np
    # anything bigger than a big room is the unenclosed hall, not the room the point meant
    dist = [(cv2.pointPolygonTest(np.array(u['polygon'], np.float32), (float(x), float(y)), True), u) for u in unlabelled if u['area'] <= 150000]
    hits = [u for d, u in dist if d >= 0]
    if hits:
        return min(hits, key=lambda u: u['area'])
    # the point may sit on a line (e.g. the centre of an elevator's X): take the nearest region
    d, u = max(dist, key=lambda t: t[0])
    return u if d >= -8 else None


def fmt_extra(extra):
    parts = []
    for k, v in extra.items():
        if isinstance(v, list):
            parts.append(f"{k}: [{', '.join(ts_str(t) for t in v)}]")
        else:
            parts.append(f'{k}: {ts_str(v)}')
    return '{ ' + ', '.join(parts) + ' }'


def main(workdir, out_dir):
    data = load(workdir)
    x0, y0, w, h = frame(data)
    for fid, d in data.items():
        emit_floor(fid, d, x0, y0, out_dir)
    open(os.path.join(out_dir, 'frame.ts'), 'w').write(
        '// GENERATED by tools/trace_cad/emit_ts.py — do not edit by hand.\n'
        '/** Shared floor frame: every level is drawn in this coordinate box. */\n'
        f'export const FRAME = {{ width: {w:.0f}, height: {h:.0f} }};\n'
    )
    print(f'frame {w:.0f} x {h:.0f}')


if __name__ == '__main__':
    main(sys.argv[1], sys.argv[2])
