"""Write src/data/gateway/level*.ts from the <floor>_rooms.json files.

Usage: python3 emit_ts.py <workdir> <src/data/gateway dir>

Every floor is mapped into one shared frame: the PDF point grid of the upper-floor sheets
(which are all drawn in the same position), shifted so the building starts near the origin.
The Lower Level sheet is drawn at another scale and rotation and is registered with the
similarity transform in floors.py.

The frame origin is recorded in frame.ts (`ORIGIN`), so a single floor can be regenerated
(`gen.py ... 4`) into a workdir holding only that floor and still land in the shared frame.
"""
import json
import math
import os
import re
import sys

from floors import FLOORS, category, display_name, wing

PAD = 20.0


def similarity(t):
    if not t:
        return lambda x, y: (x, y)
    s, deg, dx, dy = t
    c, si = math.cos(math.radians(deg)) * s, math.sin(math.radians(deg)) * s
    return lambda x, y: (c * x - si * y + dx, si * x + c * y + dy)


def load(workdir):
    data = {}
    for fid, cfg in FLOORS.items():
        path = os.path.join(workdir, f"{cfg['pdf']}_rooms.json")
        if not os.path.exists(path):
            print('missing', path)
            continue
        data[fid] = json.load(open(path))
    return data


def xy(poly):
    """The plain [x, y] vertices of a polygon whose points may carry a bulge."""
    return [[float(p[0]), float(p[1])] for p in poly]


def box_of(poly):
    """Bounding rectangle of a polygon aligned with its longest edge (restrooms, elevators
    and stairs are boxes; a traced region full of fixtures may be blobby, but its longest
    edge is a wall)."""
    import numpy as np
    P = np.array(xy(poly), float)
    D = np.roll(P, -1, axis=0) - P
    d = D[np.argmax(np.linalg.norm(D, axis=1))]
    ang = np.arctan2(d[1], d[0])
    R = np.array([[np.cos(-ang), -np.sin(-ang)], [np.sin(-ang), np.cos(-ang)]])
    Q = P @ R.T
    x0, y0 = Q.min(0)
    x1, y1 = Q.max(0)
    box = np.array([[x0, y0], [x1, y0], [x1, y1], [x0, y1]]) @ R
    return [[float(x), float(y)] for x, y in box]


BOXED_TAGS = {'restroom', 'elevator', 'stairs'}


def ellipse_of(poly, n=48):
    """The ellipse fitted to a polygon, as arcs (a third value on a vertex is the bulge)."""
    import cv2
    import numpy as np
    from rooms import arcify
    (cx, cy), (w, h), ang = cv2.fitEllipse(np.array(xy(poly), np.float32))
    t = np.radians(ang)
    a = np.linspace(0, 2 * np.pi, n, endpoint=False)
    u, v = w / 2 * np.cos(a), h / 2 * np.sin(a)
    pts = [[float(cx + x * np.cos(t) - y * np.sin(t)), float(cy + x * np.sin(t) + y * np.cos(t))] for x, y in zip(u, v)]
    return arcify(pts, tol=1.0)


def frame(data):
    xs, ys = [], []
    for fid, d in data.items():
        tf = similarity(FLOORS[fid]['transform'])
        for o in d['outlines']:
            for x, y in xy(o):
                X, Y = tf(x, y)
                xs.append(X)
                ys.append(Y)
    x0, y0 = min(xs) - PAD, min(ys) - PAD
    return x0, y0, max(xs) - x0 + PAD, max(ys) - y0 + PAD


def read_frame(path):
    """(x0, y0, width, height) from an existing frame.ts."""
    src = open(path).read()
    f = re.search(r'FRAME = \{ width: ([\d.]+), height: ([\d.]+) \}', src)
    o = re.search(r'ORIGIN = \{ x: ([\d.-]+), y: ([\d.-]+) \}', src)
    if not f or not o:
        raise SystemExit(f'{path} has no FRAME/ORIGIN; run with every floor present to define the frame')
    return float(o.group(1)), float(o.group(2)), float(f.group(1)), float(f.group(2))


def fmt_poly(poly):
    return '[' + ', '.join(f'[{p[0]:.1f}, {p[1]:.1f}]' if len(p) < 3 or not p[2] else f'[{p[0]:.1f}, {p[1]:.1f}, {p[2]:.4f}]' for p in poly) + ']'


def ts_str(s):
    return "'" + s.replace('\\', '\\\\').replace("'", "\\'") + "'"


def emit_floor(fid, d, x0, y0, out_dir):
    cfg = FLOORS[fid]
    tf = similarity(cfg['transform'])
    to_frame = lambda poly: [(lambda q, rest: (q[0] - x0, q[1] - y0, *rest))(tf(p[0], p[1]), p[2:]) for p in poly]
    lines = []
    lines.append(f"// GENERATED by tools/trace_cad/emit_ts.py from the CAD plan 'Gateway_Plan_View_10_2_2025-Floor_{cfg['pdf']}.pdf' — do not edit by hand.")
    lines.append('// Coordinates are the shared floor frame (PDF points of the upper-floor sheets, origin shifted; see tools/trace_cad/README.md).')
    lines.append("import type { PoiSpec, RoomSpec } from './floor';")
    lines.append("import type { XY } from '../helpers';")
    lines.append('')
    outlines = [to_frame(o) for o in d['outlines']]
    lines.append(f'export const outline: XY[] = {fmt_poly(outlines[0])};')
    lines.append('export const islands: XY[][] = [' + ', '.join(fmt_poly(o) for o in outlines[1:]) + '];')
    lines.append('')
    lines.append('/** Desks in the open workspaces (worksurface outlines), drawn for orientation only. */')
    lines.append('export const desks: XY[][] = [' + ', '.join(fmt_poly(to_frame(dsk)) for dsk in d.get('desks', [])) + '];')
    lines.append('')
    lines.append('export const rooms: RoomSpec[] = [')
    seen = {}
    for r in sorted(d['rooms'], key=lambda r: (r['kind'] != 'room', r['id'])):
        if r['id'] in cfg['skip'] or not r.get('polygon'):
            continue
        rid = r['id']
        seen[rid] = seen.get(rid, 0) + 1
        if seen[rid] > 1:
            rid = f"{rid}-{seen[rid]}"
        cat = category(r['name'], r['id'])
        name = display_name(r['name'], r['id'])
        w = wing(r['id'])
        extra = {'name': name, 'label': r['id']}
        if r.get('holes'):
            extra['holes'] = [to_frame(h) for h in r['holes']]
        tags = [t for t in r['name'].lower().replace('/', ' ').split() if len(t) > 2 and t not in {'the', 'and'}]
        if r['kind'] == 'open':
            tags.append('open plan')
        if tags:
            extra['tags'] = tags
        lines.append(f"  [{ts_str(w) if w else 'undefined'}, {ts_str(rid)}, {ts_str(cat)}, {fmt_poly(to_frame(r['polygon']))}, {fmt_extra(extra)}],")
    from shapely.geometry import MultiPolygon, Polygon
    placed = [Polygon(xy(r['polygon'])).buffer(0) for r in d['rooms'] if r.get('polygon')]
    resolved = []
    for px, py, uid, cat, name, label, tags in cfg['named']:
        points = px if isinstance(px, list) else [(px, py)]
        regions = []
        for qx, qy in points:
            u = region_at(d['unlabelled'], qx, qy)
            if u is not None and all(u is not r for r in regions):
                regions.append(u)
        if not regions:
            print(f'  floor {fid}: no unlabelled region at {points} for {uid}')
            continue
        resolved.append((uid, cat, name, label, tags, points, regions))
    # Several named entries may resolve to one region (three elevator shafts whose X marks
    # merge into a single cluster): split that region between them by nearest point.
    for uid, cat, name, label, tags, points, regions in resolved:
        sharers = [o for o in resolved if len(o[6]) == 1 and len(regions) == 1 and o[6][0] is regions[0]]
        if len(sharers) > 1:
            parts = split_shared(regions[0]['polygon'], [o[5][0] for o in sharers])
            poly = parts[[o[0] for o in sharers].index(uid)]
        else:
            poly = regions[0]['polygon'] if len(regions) == 1 else union_polys([r['polygon'] for r in regions])
        if 'atrium' in tags:  # the atrium is an oval: a clean ellipse through its traced outline
            poly = ellipse_of(poly)
        elif BOXED_TAGS & set(tags):
            poly = box_of(poly)
            g = Polygon(poly).buffer(0)  # a box may reach into a neighbour: trim it
            for other in placed:
                if g.intersects(other) and g.intersection(other).area > 2:
                    g = g.difference(other)
                    if isinstance(g, MultiPolygon):
                        g = max(g.geoms, key=lambda q: q.area)
            poly = [[float(x), float(y)] for x, y in g.simplify(0.3).exterior.coords[:-1]]
        placed.append(Polygon(xy(poly)).buffer(0))
        extra = {'name': name, 'label': label, 'tags': tags}
        w = wing(uid) or ('Northeast' if uid.startswith('ne-') else 'Southwest' if uid.startswith('sw-') else None)
        lines.append(f"  [{ts_str(w) if w else 'undefined'}, {ts_str(uid)}, {ts_str(cat)}, {fmt_poly(to_frame(poly))}, {fmt_extra(extra)}],")
    for uid, cat, name, label, tags, poly in cfg['manual']:
        extra = {'name': name, 'label': label, 'tags': tags}
        w = wing(uid)
        poly = clip_to(poly, d['outlines'])
        lines.append(f"  [{ts_str(w) if w else 'undefined'}, {ts_str(uid)}, {ts_str(cat)}, {fmt_poly(to_frame(poly))}, {fmt_extra(extra)}],")
    lines.append('];')
    lines.append('')
    lines.append('export const pois: PoiSpec[] = [')
    for i, (ex, ey) in enumerate(d.get('exits', []), 1):
        X, Y = tf(ex, ey)
        lines.append(f"  ['entrance-{i}', 'Entrance {i}', 'exit', [{X - x0:.1f}, {Y - y0:.1f}]],")
    for pid, name, kind, (px, py), *desc in cfg['pois']:
        X, Y = tf(px, py)
        lines.append(f"  [{ts_str(pid)}, {ts_str(name)}, {ts_str(kind)}, [{X - x0:.1f}, {Y - y0:.1f}]{', ' + ts_str(desc[0]) if desc else ''}],")
    lines.append('];')
    lines.append('')
    open(os.path.join(out_dir, f'level{fid}.ts'), 'w').write('\n'.join(lines))
    print(f'level{fid}.ts: {len(d["rooms"])} rooms + {len(cfg["named"])} named regions, {len(d.get("desks", []))} desks')


def clip_to(poly, outlines):
    """Intersection of a hand polygon with the floor outline(s), via a 1 px/pt raster."""
    import cv2
    import numpy as np
    pts = np.array(xy(poly), np.float32)
    x0, y0 = np.floor(pts.min(0)).astype(int) - 2
    x1, y1 = np.ceil(pts.max(0)).astype(int) + 2
    a = np.zeros((y1 - y0, x1 - x0), np.uint8)
    b = np.zeros_like(a)
    cv2.fillPoly(a, [np.round(pts - [x0, y0]).astype(np.int32)], 255)
    for o in outlines:
        cv2.fillPoly(b, [np.round(np.array(xy(o)) - [x0, y0]).astype(np.int32)], 255)
    cs, _ = cv2.findContours(a & b, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
    if not cs:
        return poly
    c = cv2.approxPolyDP(max(cs, key=cv2.contourArea), 1.5, True).reshape(-1, 2) + [x0, y0]
    return [[float(x), float(y)] for x, y in c]


def split_shared(poly, points):
    """Split a polygon between seed points (nearest point wins); each part is boxed, since
    the regions that share one polygon are elevator shafts."""
    import cv2
    import numpy as np
    pts = np.array(xy(poly), np.float32)
    x0, y0 = np.floor(pts.min(0)).astype(int) - 2
    x1, y1 = np.ceil(pts.max(0)).astype(int) + 2
    a = np.zeros((y1 - y0, x1 - x0), np.uint8)
    cv2.fillPoly(a, [np.round(pts - [x0, y0]).astype(np.int32)], 255)
    ys, xs = np.nonzero(a)
    P = np.array(points, float) - [x0, y0]
    owner = ((xs[:, None] - P[None, :, 0]) ** 2 + (ys[:, None] - P[None, :, 1]) ** 2).argmin(1)
    out = []
    for i in range(len(points)):
        part = np.zeros_like(a)
        part[ys[owner == i], xs[owner == i]] = 255
        cs, _ = cv2.findContours(part, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
        if not cs:
            out.append(poly)
            continue
        box = cv2.boxPoints(cv2.minAreaRect(max(cs, key=cv2.contourArea))) + [x0, y0]
        out.append([[float(x), float(y)] for x, y in box])
    # the boxes are fitted independently, so trim each by the ones before it
    from shapely.geometry import MultiPolygon, Polygon
    trimmed = []
    for b in out:
        g = Polygon(b).buffer(0)
        for t in trimmed:
            g = g.difference(t)
            if isinstance(g, MultiPolygon):
                g = max(g.geoms, key=lambda q: q.area)
        trimmed.append(g)
    return [[[float(x), float(y)] for x, y in g.simplify(0.3).exterior.coords[:-1]] for g in trimmed]


def union_polys(polys):
    """Outer contour of the union of polygons (closed by a few px so touching flights join)."""
    import cv2
    import numpy as np
    pts = np.concatenate([np.array(xy(p), np.float32) for p in polys])
    x0, y0 = np.floor(pts.min(0)).astype(int) - 6
    x1, y1 = np.ceil(pts.max(0)).astype(int) + 6
    a = np.zeros((y1 - y0, x1 - x0), np.uint8)
    for p in polys:
        cv2.fillPoly(a, [np.round(np.array(xy(p)) - [x0, y0]).astype(np.int32)], 255)
    a = cv2.morphologyEx(a, cv2.MORPH_CLOSE, np.ones((9, 9), np.uint8))
    cs, _ = cv2.findContours(a, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
    c = cv2.approxPolyDP(max(cs, key=cv2.contourArea), 2.0, True).reshape(-1, 2) + [x0, y0]
    return [[float(x), float(y)] for x, y in c]


def region_at(unlabelled, x, y):
    """The unlabelled region whose polygon contains (x, y), smallest first."""
    import cv2
    import numpy as np
    # anything bigger than a big room is the unenclosed hall, not the room the point meant
    dist = [(cv2.pointPolygonTest(np.array(xy(u['polygon']), np.float32), (float(x), float(y)), True), u) for u in unlabelled if u['area'] <= 150000]
    hits = [u for d, u in dist if d >= 0]
    if hits:
        return min(hits, key=lambda u: u['area'])
    # the point may sit on a line (e.g. the centre of an elevator's X): take the nearest region
    d, u = max(dist, key=lambda t: t[0])
    return u if d >= -8 else None


def fmt_extra(extra):
    parts = []
    for k, v in extra.items():
        if k == 'holes':
            parts.append(f"{k}: [{', '.join(fmt_poly(h) for h in v)}]")
        elif isinstance(v, list):
            parts.append(f"{k}: [{', '.join(ts_str(t) for t in v)}]")
        else:
            parts.append(f'{k}: {ts_str(v)}')
    return '{ ' + ', '.join(parts) + ' }'


def main(workdir, out_dir):
    data = load(workdir)
    frame_path = os.path.join(out_dir, 'frame.ts')
    if len(data) < len(FLOORS) and os.path.exists(frame_path):
        # Only some floors were traced: keep the frame the other levels are already drawn in.
        x0, y0, w, h = read_frame(frame_path)
        print(f'floors {", ".join(sorted(data))} only: keeping the existing frame')
    else:
        x0, y0, w, h = frame(data)
        open(frame_path, 'w').write(
            '// GENERATED by tools/trace_cad/emit_ts.py — do not edit by hand.\n'
            '/** Shared floor frame: every level is drawn in this coordinate box. */\n'
            f'export const FRAME = {{ width: {w:.0f}, height: {h:.0f} }};\n'
            '/** Sheet point (upper-floor PDFs) at the frame origin; lets one floor be regenerated alone. */\n'
            f'export const ORIGIN = {{ x: {x0:.0f}, y: {y0:.0f} }};\n'
        )
        print(f'frame {w:.0f} x {h:.0f}')
    for fid, d in data.items():
        emit_floor(fid, d, x0, y0, out_dir)


if __name__ == '__main__':
    main(sys.argv[1], sys.argv[2])
